import Head from "next/head";
import Image from "next/image";
import Map from "../components/Map";
import styles from "../styles/Home.module.css";
import { Wrapper, Status } from "@googlemaps/react-wrapper";

export default function Home() {
  const render = (status) => {
    switch (status) {
      case Status.LOADING:
        return <p>Loading...</p>;
      case Status.FAILURE:
        return <p>There was an error</p>;
      case Status.SUCCESS:
        return <Map />;
    }
  };
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>PickMeUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-full">
        <Wrapper apiKey={"AIzaSyCXLrz-WThV4cNntmzzW4w75L7uwqU-u14"} render={render} />
      </div>
    </div>
  );
}
